# Q- 1 Write Statement to 'import' numpy

In [15]:
import numpy as np

# Q - 2 Create a array using Numpy

In [16]:
my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

# Q-3 Create a array of ten numbers

In [17]:
my_array = np.random.randint(1,10,4)
my_array

array([7, 8, 4, 1])

# Q-4 Create an array of elements from 10-20

In [18]:
import numpy as np
my_array = np.arange(10,21)
my_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Q- 5 Create an array which contains value 5 , 10 times ? 

In [19]:
my_array = np.random.randint(5,6,10)
my_array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# Q-6 Create a one dimensional array and convert that into 3*3 matrix ? 

In [20]:
my_array = np.array([1,2,3,4,5,6,7,8,9])
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_array = my_array.reshape(3,3)
my_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Q- 7 Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ? 

In [22]:
my_array = np.random.rand(9)
my_array = my_array.reshape(3,3)
my_array

array([[0.11986978, 0.29506091, 0.69920544],
       [0.29389783, 0.0535026 , 0.49485375],
       [0.69126779, 0.70127697, 0.9107237 ]])

# Q-8 Concatenate 2D array horizontally and vertically ?

In [30]:
ar1 = np.array([[10,20,30],[1,2,3]])
ar2 = np.array([[11,21,31],[10,20,30]])

horizontal = np.concatenate((ar1,ar2),axis = 1)
vertical = np.concatenate((ar1,ar2),axis = 0)

vertical

array([[10, 20, 30],
       [ 1,  2,  3],
       [11, 21, 31],
       [10, 20, 30]])

In [31]:
horizontal

array([[10, 20, 30, 11, 21, 31],
       [ 1,  2,  3, 10, 20, 30]])